from datetime import datetime
from typing import Literal, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict

DocumentType = Literal["claim_form", "prescription", "other"]


class UploadResponse(BaseModel):
    id: UUID
    s3_url: str
    original_filename: str
    status: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SubmittedDocumentsChecklist(BaseModel):
    claim_form_signed: Optional[Literal["Y", "N"]] = None
    hospital_main_bill: Optional[Literal["Y", "N"]] = None
    hospital_breakup_bill: Optional[Literal["Y", "N"]] = None
    hospital_discharge_summary: Optional[Literal["Y", "N"]] = None
    pharmacy_bill: Optional[Literal["Y", "N"]] = None


class BankDetails(BaseModel):
    bank_name: Optional[str] = None
    account_number: Optional[str] = None
    ifsc_code: Optional[str] = None


class ClaimExpensesSummary(BaseModel):
    pre_hospitalization: Optional[str] = None
    hospitalization: Optional[str] = None
    post_hospitalization: Optional[str] = None
    total_claimed_amount: Optional[str] = None
    pre_hospitalization_period_days: Optional[str] = None


class HospitalizationInfo(BaseModel):
    room_category: Optional[str] = None
    hospitalization_due_to: Optional[str] = None
    injury_cause: Optional[str] = None
    date_of_admission: Optional[str] = None
    time_of_admission: Optional[str] = None
    date_of_discharge: Optional[str] = None
    time_of_discharge: Optional[str] = None


class PatientHospitalizedDetails(BaseModel):
    name: Optional[str] = None
    gender: Optional[str] = None
    relationship_to_primary_insured: Optional[str] = None
    occupation: Optional[str] = None
    hospital_name: Optional[str] = None


class PrimaryInsuredDetails(BaseModel):
    policy_no: Optional[str] = None
    tpa_id_no: Optional[str] = None
    name: Optional[str] = None
    address: Optional[str] = None
    city: Optional[str] = None
    pin_code: Optional[str] = None
    email_id: Optional[str] = None
    pan: Optional[str] = None


class Medicine(BaseModel):
    name: Optional[str] = None
    dosage: Optional[str] = None
    frequency: Optional[str] = None
    duration: Optional[str] = None
    notes: Optional[str] = None


class PrescriptionDetails(BaseModel):
    doctor_name: Optional[str] = None
    doctor_registration_no: Optional[str] = None
    clinic_or_hospital_name: Optional[str] = None
    patient_name: Optional[str] = None
    patient_age: Optional[str] = None
    patient_gender: Optional[str] = None
    date_of_visit: Optional[str] = None
    diagnosis_or_complaint: Optional[str] = None
    medicines: Optional[list[Medicine]] = None
    advice_notes: Optional[str] = None
    follow_up_date: Optional[str] = None


class ClaimFormDetails(BaseModel):
    """Groups the existing claim-form-only fields under one optional section."""

    primary_insured_details: Optional[PrimaryInsuredDetails] = None
    patient_hospitalized_details: Optional[PatientHospitalizedDetails] = None
    hospitalization_info: Optional[HospitalizationInfo] = None
    claim_expenses_summary: Optional[ClaimExpensesSummary] = None
    bank_details: Optional[BankDetails] = None
    submitted_documents_checklist: Optional[SubmittedDocumentsChecklist] = None


class ClaimExtractionPayload(BaseModel):
    document_type: Optional[DocumentType] = None
    tpa_name: Optional[str] = None
    overall_confidence: Optional[Literal["high", "medium", "low"]] = None
    claim_details: Optional[ClaimFormDetails] = None
    prescription_details: Optional[PrescriptionDetails] = None


class ExtractionSummary(BaseModel):
    """Generated by our service, NOT by Gemini - stamped after extraction completes."""

    file_name: str
    status: str
    extraction_timestamp: datetime


class ClaimExtractionResult(BaseModel):
    """Full response shape returned to the frontend by GET /claims/{id} - combines our stamped summary with Gemini's payload."""

    extraction_summary: ExtractionSummary
    extraction_data: ClaimExtractionPayload
